### ISSUE TITLE
Condition with queryset

### ISSUE THREAD

**Issue by axsapronov** [RevolutionTech/django-conditions#2]
Hi.

Your library is good! 
Can you add or explain me how to add new condition type?
`CompareCondition` works with `int/float/str`. And you input your value (`operand`) in `input` HTML element.
I want write conditions with `select` HTML element (for example, choose one of list element, item of queryset)

Example:

```python
# models
class Label(models.Model):
     name = models.CharField(max_length=255)

class Settings(models.Model):
     name = models.CharField(max_length=255)
     conditions = ConditionsField(definitions=conditions_from_module(...))

# and condition
class LabelCondition(Condition):
     condstr = 'label_item'
     queryset = Label.objects.all()

    def eval_operand(self, user, **kwargs):
         pass  # some code with selected label
```

And then I want choice an element of queryset and use it as `operand` variable.

**Comment by RevolutionTech** [comment]
I am not 100% certain if I understand your use case exactly, but perhaps you can accomplish what you are looking for with keys and the `keys_allowed` property.

For example, in one application where I am using django-conditions, I have a condition that is based on the mobile OS of the client. It looks something like this:
```python
class MobileOS(Condition):
    """
    A condition where the user is using a particular mobile OS
    """

    condstr = 'MOBILE_OS'
    keys_allowed = ['IOS', 'ANDROID']

    def eval_bool(self, user, **kwargs):
        mobile_os = kwargs['request'].mobile_os
        return mobile_os == self.key
```

In my conditions widget, this result in a dropdown where the admin can select between `IOS` and `ANDROID`.

In your particular case, it looks like you would want `keys_allowed` to be evaluated based on a queryset. Learn more about how keys work in conditions here:
http://django-conditions.readthedocs.io/en/latest/keys.html

**Comment by axsapronov** [comment]
Yeah!
It works for me.

Thanks.

**Comment by RevolutionTech** [comment]
Awesome! I'm glad that's working for you.
